### ISSUE TITLE
[Feature Request] ReCaptcha

### ISSUE THREAD

**Issue by lachieh** [Stillat/meerkat#1]
It would be really great if the comment forms also worked with the [reCaptcha addon](https://statamic.com/marketplace/addons/google-recaptcha) (or if Meerkat had built-in reCaptcha support). Akismet is great, but reCaptcha is free.

I believe this has something to do with the way that the forms are being handled. Perhaps because it never submits comments through the standard Statamic form handler so it never triggers the `Form.submission.creating` that the reCaptcha addon listens for.

Would this be possible to build something that implements the `SpamDetector` interface? The methods look pretty straight forward though I wasn't sure where to start to get it the new class registered with the `Guard`.

**Comment by JohnathonKoster** [comment]
@lachieh 

The latest versions of Meerkat now emit internal events that allow for compatibility with the reCaptcha addon. You can get the latest version (1.5.73) from the Statamic Marketplace https://statamic.com/marketplace/addons/meerkat

**Comment by lachieh** [comment]
Thank you!
