### ISSUE TITLE
Please respond

### ISSUE THREAD

**Issue by keeslina** [Stillat/meerkat#2]
Hi

Ik tried to email you multiple times but no response.

I'm facing two problems :

1. License is not activated, even though I added the domain to my account on your website
2. I really would like to be able to grant permissions for comment moderation to non super admins... Is this in any way possible? I don't want to give my client a super admin account...

Thanks !

**Comment by JohnathonKoster** [comment]
@keeslina Sent out an email with a solution on the license item, and am looking into the super admin issue

**Comment by JohnathonKoster** [comment]
Moving permissions handling to https://github.com/Stillat/meerkat-v1hub/issues/19

**Comment by keeslina** [comment]
Hi John,

Thanks very much for your work! Everything works the way I expect now 👍👍
